#!/bin/bash

function help () {
    echo "Usage: see [OPTION...] FILE"
    echo ""
    echo "  -v --version    Print version information"
    echo "  --help          Show this screen"
    echo ""
    echo "Mandatory or optional arguments to long options are also mandatory or optional"
    echo "for any corresponding short options."
    echo ""
    echo "Report bugs to henri.sendelbach+see@proton.me."
}

if [ -z "$1" ]; then
    help;
    exit 1;
fi

if [ "$1" == "-v" ] || [ "$1" == "--version" ]; then
    echo "See v1.0.0"
    exit 0
fi

if [ "$1" == "--help" ]; then
    help;
    exit 0
fi

if [ ! -f "$1" ]; then
    echo "Error: File '$1' does not exist."
    exit 1
fi

pygmentize -g "$1" | \
    nl -ba -w \
        $(wc -l < "$1" | awk '{print length}') \
    -s $' | \033[0m' | \
    sed 's/^/\x1b[90m/' | \
    less -R
