name: See Install Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: sudo make install

    - name: Run check
      run: cat /usr/bin/see

    - name: Run Test
      run: see -v
